### ISSUE TITLE
Could you explain how src/tracers/js/worker.js works?

### ISSUE THREAD

**Issue by Wizard-F** [algorithm-visualizer/server#11]
Hi, I find your awesome project recently and have started to read its code to understand how the system works. 

I'm puzzled by [src/tracers/js/worker.js](https://github.com/algorithm-visualizer/server/blob/0d6dec45c3b3a62f826667b4288f3fbc094ebaf1/src/tracers/js/worker.js) as shown below. What is the `AlgorithmVisualizer` here? I can't find it elsewhere, not even in the [Algorithm Visualizer repo](https://github.com/algorithm-visualizer).

```
const process = { env: { ALGORITHM_VISUALIZER: '1' } };
importScripts('/api/tracers/js');

const sandbox = code => {
  const require = name => ({ 'algorithm-visualizer': AlgorithmVisualizer }[name]); // fake require
  eval(code);
};

onmessage = e => {
  const lines = e.data.split('\n').map((line, i) => line.replace(/(\.\s*delay\s*)\(\s*\)/g, `$1(${i})`));
  const code = lines.join('\n');
  sandbox(code);
  postMessage(AlgorithmVisualizer.Commander.commands);
};
```

**Comment by 64json** [comment]
Hi @Wizard-F, glad you find it awesome.

`importScripts('/api/tracers/js');` will import [the script on unpkg](https://github.com/algorithm-visualizer/server/blob/0d6dec45c3b3a62f826667b4288f3fbc094ebaf1/src/tracers/js/JsTracer.ts#L23), which defines `global.AlgorithmVisualizer`.

**Comment by unfode** [comment]
Thanks!

But what is the content (or source code) of `https://unpkg.com/algorithm-visualizer@${version}/dist/algorithm-visualizer.umd.js`? How does `eval(code)` generate the visualization commands in `postMessage(AlgorithmVisualizer.Commander.commands)`?

https://github.com/algorithm-visualizer/server/blob/9ac17dff65ce10e9e513fc4d3c7b7b9a048dc529/src/tracers/js/worker.js#L1-L14

**Comment by 64json** [comment]
https://github.com/algorithm-visualizer/tracers.js/tree/master/src is the source code of https://unpkg.com/algorithm-visualizer/dist/algorithm-visualizer.umd.js.

`eval(code)` runs the code having calls to tracers, and the tracers collect visualization commands in `AlgorithmVisualizer.Commander.commands`.

**Comment by Wizard-F** [comment]
Thanks! It's a lot clearer to me now : )

What's the node version for Algorithm Visualizer projects? I'm using node v16 and have bugs with `npm install`. I can't find the node version anywhere.
